name: CmdRank
main: me.flungo.bukkit.cmdrank.CmdRank
version: 1.1.1
author: flungo
description: >
             Ranks up players by executing commands
depend:
  - Vault
commands:
  rankup:
    description: Rankup a user based on defined rules and requirements
    usage: |
        /<command> - Ranks up the player to their next rank
  rankcheck:
    description: List all rankups that will be executed when /rankup is executed with their requirements
    usage: |
        /<command> - Shows all rankups that will be attempted when /rankup is executed and their requirements
  cmdrank:
    description: Admin command for controlling CmdRank
    usage: |
        /<command> reload - Reloads the config file
permissions:
  cmdrank.admin:
    description: Access to admin commands.
  cmdrank.rankup:
    description: Allows player to use the command.
  cmdrank.bypass.cooldown:
    description: Bypass the cooldown time with this permission
  cmdrank.bypass.disabled:
    description: Bypass disabled rankups - there is no rankup limit for disabled rankups
  cmdrank.bypass.reranks:
    description: Bypass rerank lmits