#Defined ranks
ranks:
  #Use same name as name of rank in permissions plugin - all subnodes of the rankname are optional
  default:
    description: You will rank up from default to member and receive 2 diamonds
    #What the user must have before they can rankup (Set to 0 to disable)
    #DO NOT use negative values
    requirements:
      money: 500
      exp: 50
      health: 10
      hunger: 10
    #Commands to execute when ranking up the player
    commands:
      # Example using pex ladder
      - "pex promote {player} ladder"
      # Example adding a user to the group member then removing from their old group in 2 commands
      - "pex user {player} group add member"
      - "pex user {player} group remove {rank}"
      # Example of giving them a rankup gift
      - "give {player} diamond 2"
    announcement: "{player} has ranked up from default to member"
    #Minimum time in seconds between rankups that match this
    #(0 to disable)
    cooldown: 0
    #Maximum number of times a player can use this rankup
    #(0 will disable rank, negative will make infinite, -1 is default, n > 0 will allow n uses)
    reranks: -1
#Will requirements be used (true) or just checked (false)
use-requirements:
  money: true
  exp: true
  health: false
  hunger: false
#Minimum time in seconds between rankups (0 to disable)
cooldown: 0
#Can a player use any rank match more than once?
#Be careful if players are demoted and this is set to false.
#Provides better compatability with some permissions plugins when set to false.
rerank: true
#Is the plugin enabled (i.e. Can players use it)
enable: true
#Display extra information in the console for debugging
debug: false