#Will requirements be used (true) or just checked (false)
use-requirements:
  money: true
  exp: true
  health: false
  hunger: false
#Minimum time in seconds between rankups (0 to disable)
cooldown: 0
#Can a player use any rank match twice? Be careful if players are demoted and this is set to false. Provides better compatability with some permissions plugins when set to false.
rerank: true
#Is the plugin enabled (i.e. Can players use it)
enable: true
#Display extra information in the console for debugging
debug: false